"""empty message

Revision ID: fc0d33ee9abf
Revises: 
Create Date: 2017-01-04 16:17:05.392739

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fc0d33ee9abf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('word', sa.Column('leading_phones', sa.String(length=20), nullable=True))
    op.add_column('word', sa.Column('trailing_phones', sa.String(length=20), nullable=True))
    op.alter_column('word', 'definition',
               existing_type=mysql.TEXT(),
               nullable=True)
    op.alter_column('word', 'word',
               existing_type=mysql.VARCHAR(length=25),
               nullable=True)
    op.alter_column('word', 'wordtype',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('word', 'wordtype',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)
    op.alter_column('word', 'word',
               existing_type=mysql.VARCHAR(length=25),
               nullable=False)
    op.alter_column('word', 'definition',
               existing_type=mysql.TEXT(),
               nullable=False)
    op.drop_column('word', 'trailing_phones')
    op.drop_column('word', 'leading_phones')
    # ### end Alembic commands ###
